"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { Menu, ShoppingBag, UserRound, Upload, ArrowUpRight, X } from "lucide-react";

const nav = [["Portrait","/portrait"],["Impact","/impact"],["Community","/community"],["Human Shop","/human-shop"],["About","/about"]];
const images = {
  hero: "/images/hero-whippet-coral.webp", portrait: "/images/portrait-pop-dachshund.webp",
  bedroom: "/images/bedroom-greyhound-wide.webp", statement: "/images/bedroom-statement-dog-wide.webp",
  desk: "/images/studio-desk-dog-art.webp", fashion: "/images/fashion-capsule-preview.webp",
  gallery: "/images/community-gallery-milan.webp", popup: "/images/community-popup-milan.webp",
  materials: "/images/materials-quiet-luxury.webp", smoked: "/images/interior-dachshund-smoked-glass.webp",
};

export function Header() {
  const [open,setOpen]=useState(false);
  return <header className="site-header"><Link className="wordmark" href="/">PUPSART</Link><nav className="desktop-nav" aria-label="Navigazione principale">{nav.map(([n,h])=><Link key={h} href={h}>{n}</Link>)}</nav><div className="header-actions"><Link aria-label="Account" href="/account"><UserRound/></Link><Link aria-label="Carrello" href="/cart"><ShoppingBag/></Link><Link className="button button-dark desktop-cta" href="/portrait#configuratore">Crea il tuo ritratto</Link><button className="menu-toggle" aria-label="Apri menu" onClick={()=>setOpen(true)}><Menu/></button></div>{open&&<div className="mobile-menu"><button aria-label="Chiudi menu" onClick={()=>setOpen(false)}><X/></button><Link className="wordmark" href="/">PUPSART</Link><nav>{nav.map(([n,h],i)=><Link key={h} href={h} onClick={()=>setOpen(false)}><span>0{i+1}</span>{n}</Link>)}</nav><Link className="button button-coral" href="/portrait#configuratore">Crea il tuo ritratto</Link></div>}</header>;
}

export function Footer(){return <footer><div><Link className="wordmark" href="/">PUPSART</Link><p>Art living for pet lovers.</p></div><div className="footer-links"><div><b>Esplora</b>{nav.map(([n,h])=><Link key={h} href={h}>{n}</Link>)}</div><div><b>Info</b><Link href="/privacy">Privacy</Link><Link href="/terms">Termini</Link><Link href="/shipping">Spedizioni</Link><Link href="/accessibility">Accessibilità</Link></div></div><div className="footer-bottom"><span>© 2026 Pupsart</span><span>IT / EN</span><span>Milano, Italia</span></div></footer>}

function Shell({children}: {children:React.ReactNode}){return <><Header/>{children}<Footer/></>}
function Eyebrow({children}: {children:React.ReactNode}){return <p className="eyebrow">{children}</p>}

export function Configurator({compact=false}:{compact?:boolean}){
  const [file,setFile]=useState<string|null>(null),[style,setStyle]=useState("Editorial Pop"),[phrase,setPhrase]=useState(""),[size,setSize]=useState("50 × 70 cm"),[frame,setFrame]=useState("Senza cornice"),[step,setStep]=useState(1),[error,setError]=useState("");
  const input=useRef<HTMLInputElement>(null);
  useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options?:{signal?:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();void Promise.resolve(context.registerTool({name:"stage_pupsart_portrait",title:"Configura Pupsart Portrait",description:"Imposta stile, frase, formato e cornice nella configurazione visibile. Prepara una richiesta e non effettua acquisti o upload.",inputSchema:{type:"object",properties:{style:{type:"string",enum:["Editorial Pop","Quiet Icon","Bold Character"]},phrase:{type:"string",maxLength:42},size:{type:"string",enum:["30 × 40 cm","50 × 70 cm","70 × 100 cm"]},frame:{type:"string",enum:["Senza cornice","Nero opaco","Rovere naturale"]}},required:["style","size","frame"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(raw:unknown){const v=raw as {style?:string;phrase?:string;size?:string;frame?:string};if(!v.style||!v.size||!v.frame||((v.phrase?.length??0)>42))throw new Error("Configurazione non valida");setStyle(v.style);setPhrase(v.phrase??"");setSize(v.size);setFrame(v.frame);setStep(5);document.getElementById("configuratore")?.scrollIntoView({behavior:"smooth"});return {status:"staged",style:v.style,size:v.size,frame:v.frame};}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[]);
  const load=(f?:File)=>{if(!f)return;if(!["image/jpeg","image/png","image/webp"].includes(f.type)||f.size>10*1024*1024){setError("Usa JPG, PNG o WebP fino a 10 MB.");return}setError("");setFile(URL.createObjectURL(f));setStep(Math.max(step,2))};
  return <section id="configuratore" className={`configurator ${compact?"compact":""}`}><div className="config-intro"><Eyebrow>Pupsart Portrait / Configuratore</Eyebrow><h2>Il tuo cane.<br/>Diretto come un’icona.</h2><p>Crea una direzione per il ritratto. Nessuna immagine viene inviata: questa versione prepara soltanto la richiesta.</p><div className="steps" aria-label={`Passaggio ${step} di 5`}>{[1,2,3,4,5].map(n=><span key={n} className={n<=step?"active":""}>{String(n).padStart(2,"0")}</span>)}</div></div><div className="config-workspace"><div className="upload-panel" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();load(e.dataTransfer.files[0])}}>{file?<img src={file} alt="Anteprima locale della foto caricata"/>:<Image src={images.portrait} fill sizes="(max-width: 800px) 100vw, 45vw" alt="Ritratto Pupsart di un bassotto su fondo coral e nero"/>}<button className="upload-button" onClick={()=>input.current?.click()}><Upload/> {file?"Cambia foto":"Carica o trascina una foto"}</button><input ref={input} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>load(e.target.files?.[0])}/>{error&&<p className="form-error" role="alert">{error}</p>}<span className="concept-note">Preview concettuale · nessuna generazione AI</span></div><div className="config-controls"><fieldset><legend>01 / Stile</legend><div className="choice-grid">{["Editorial Pop","Quiet Icon","Bold Character"].map(v=><button key={v} className={style===v?"selected":""} onClick={()=>{setStyle(v);setStep(Math.max(step,3))}}><span className={`swatch swatch-${v.split(" ")[0].toLowerCase()}`}/>{v}</button>)}</div></fieldset><label>02 / Frase opzionale<textarea maxLength={42} value={phrase} onChange={e=>{setPhrase(e.target.value);setStep(Math.max(step,4))}} placeholder="MAIN CHARACTER ENERGY."/><span>{phrase.length}/42</span></label><div className="suggestions">{["GOOD TASTE. GREAT DOGS.","SAME ICON. DIFFERENT SPECIES."].map(x=><button key={x} onClick={()=>setPhrase(x)}>{x}</button>)}</div><fieldset><legend>03 / Formato</legend><div className="inline-choices">{["30 × 40 cm","50 × 70 cm","70 × 100 cm"].map(v=><button key={v} className={size===v?"selected":""} onClick={()=>{setSize(v);setStep(5)}}>{v}</button>)}</div></fieldset><label>04 / Cornice<select value={frame} onChange={e=>setFrame(e.target.value)}><option>Senza cornice</option><option>Nero opaco</option><option>Rovere naturale</option></select></label><div className="summary"><Eyebrow>La tua direzione</Eyebrow><dl><div><dt>Stile</dt><dd>{style}</dd></div><div><dt>Formato</dt><dd>{size}</dd></div><div><dt>Cornice</dt><dd>{frame}</dd></div></dl><Link className="button button-coral" href="/portrait#richiesta">Continua la richiesta <ArrowUpRight/></Link></div></div></div></section>
}

export function HomePage(){return <Shell><main><section className="hero"><Image src={images.hero} fill priority sizes="100vw" alt="Donna in cappotto nero con whippet davanti a un grande ritratto pop su set coral"/><div className="hero-shade"/><div className="hero-copy"><Eyebrow>Pop art living / Milano</Eyebrow><h1>MAKE ROOM FOR<br/>YOUR MAIN CHARACTER.</h1><p>Pupsart trasforma il tuo cane in un’icona da appendere, vivere e portare con te.</p><div><Link className="button button-coral" href="#configuratore">Crea il tuo ritratto</Link><Link className="text-link light" href="/portrait">Scopri Pupsart Portrait <ArrowUpRight/></Link></div></div><span className="edition">COLLECTION 01 / 2026</span></section><section className="manifesto"><Eyebrow>Manifesto 01</Eyebrow><h2>I cani diventano<br/><em>icone da vivere.</em></h2><div><p>Arte, casa, guardaroba e cultura urbana. Un universo costruito intorno alla relazione più spontanea che conosciamo, con la cura di una gallery shop.</p><Link className="text-link" href="/about">Dentro Pupsart <ArrowUpRight/></Link></div></section><Configurator compact/><PortraitSystem/><RealLife/><ComingSoon/><ImpactTeaser/><CommunityTeaser/><Newsletter/></main></Shell>}

function PortraitSystem(){return <section className="portrait-system"><div className="section-head"><div><Eyebrow>Pupsart Portrait System</Eyebrow><h2>Una firma visiva.<br/>Mai un filtro.</h2></div><p>Tre direzioni artistiche al lancio. Ognuna ha palette, composizione e materia proprie.</p></div><div className="style-feature"><Image src={images.portrait} fill sizes="(max-width: 800px) 100vw, 55vw" alt="Ritratto editoriale pop di un bassotto"/><div><span className="index">01 / 03</span><h3>Editorial Pop</h3><p>Campiture coral e oxblood, segno netto, grana da stampa. Il carattere entra prima del pedigree.</p><div className="palette"><i/><i/><i/><i/></div><Link className="button button-light" href="/portrait#configuratore">Scegli questo stile</Link></div></div></section>}
function RealLife(){return <section className="real-life"><div className="section-head"><div><Eyebrow>At home / At work</Eyebrow><h2>Il ritratto,<br/>nella vita reale.</h2></div><p>Un oggetto d’interni prima ancora che un ricordo. Pensato per vivere con la stanza, la carta e la luce.</p></div><div className="editorial-grid"><figure className="wide"><Image src={images.bedroom} fill sizes="66vw" alt="Camera milanese con grande ritratto di levriero sopra il letto"/><figcaption>01 / Camera di una designer, Milano</figcaption></figure><figure><Image src={images.materials} fill sizes="33vw" alt="Ritratto di levriero, tessile stampato e confezione su piano materico"/><figcaption>02 / Carta, tessile, packaging</figcaption></figure><figure><Image src={images.desk} fill sizes="33vw" alt="Scrivania creativa con piccoli artwork Pupsart"/><figcaption>03 / Dogs at work</figcaption></figure></div></section>}
function ComingSoon(){return <section className="coming"><Image src={images.fashion} fill sizes="100vw" alt="Capsule moda Pupsart con capi e accessori illustrati"/><div className="coming-copy"><Eyebrow>Capsule 02 / Coming soon</Eyebrow><h2>A BRAND YOU CAN<br/>HANG, WEAR, WALK.</h2><p>Apparel, desk objects, zine e accessori. Una collezione prima degli SKU.</p><Link className="button button-light" href="/human-shop">Entra nella waiting list</Link></div></section>}
function ImpactTeaser(){return <section className="impact-teaser"><Eyebrow>Impact / Network in costruzione</Eyebrow><h2>IL CONTRIBUTO<br/><em>SI VEDE.</em></h2><div className="impact-flow">{[["01","Ordine"],["02","Progetto identificato"],["03","Trasferimento"],["04","Update del risultato"]].map(([n,t])=><div key={n}><span>{n}</span><b>{t}</b></div>)}</div><p>Importo per ordine, partner e progetto verranno pubblicati quando definiti e verificabili.</p><Link className="text-link" href="/impact">Scopri la rete Pupsart <ArrowUpRight/></Link></section>}
function CommunityTeaser(){return <section className="community-teaser"><div className="section-head"><div><Eyebrow>Pupsart People</Eyebrow><h2>GOOD DOGS.<br/>BRIGHTER PEOPLE.</h2></div><Link className="text-link" href="/community">Entra nella community <ArrowUpRight/></Link></div><div className="community-hero"><Image src={images.gallery} fill sizes="100vw" alt="Evento Pupsart in una galleria milanese con persone e cani"/><span>MAIN CHARACTERS / MILANO</span></div></section>}
function Newsletter(){return <section className="newsletter"><Eyebrow>Private preview</Eyebrow><h2>New portraits, limited drops and good dogs.</h2><form onSubmit={e=>e.preventDefault()}><label><span className="sr-only">Email</span><input type="email" required placeholder="La tua email"/></label><button type="submit">Iscriviti <ArrowUpRight/></button></form><small>Solo nuove collezioni, storie e inviti. Niente rumore.</small></section>}

export function PortraitPage(){return <Shell><main><PageHero label="Pupsart Portrait / Collection 01" title="YOUR DOG,\nFRAMED PROPERLY." image={images.statement} alt="Camera milanese con ritratto statement di un levriero"/><section className="split-copy"><Eyebrow>Art first</Eyebrow><h2>Un ritratto su misura, trattato come un’edizione artistica.</h2><p>La foto avvia una direzione creativa. Pupsart lavora su espressione, postura, palette e composizione per costruire un artwork riconoscibile. La preview del sito non rappresenta il risultato finale.</p></section><Configurator/><section className="process"><Eyebrow>Processo</Eyebrow>{["Foto","Direzione artistica","Revisione","Produzione","Consegna"].map((x,i)=><div key={x}><span>0{i+1}</span><h3>{x}</h3><p>{["Una foto nitida, con occhi e muso leggibili.","Scegli stile, frase, formato e cornice.","Il flusso di approvazione verrà definito prima del lancio.","Materiali e finiture saranno confermati con i fornitori.","Tempi comunicati solo dopo la validazione produttiva."][i]}</p></div>)}</section><section id="richiesta" className="request"><Eyebrow>Stato del prodotto</Eyebrow><h2>Il primo drop è in preparazione.</h2><p>Prezzi, tempi, formati definitivi e politica revisioni non sono ancora pubblicati. Lascia il tuo contatto per ricevere la preview del lancio.</p><Newsletter/></section></main></Shell>}

function PageHero({label,title,image,alt}:{label:string,title:string,image:string,alt:string}){return <section className="page-hero"><Image src={image} fill priority sizes="100vw" alt={alt}/><div className="hero-shade"/><div><Eyebrow>{label}</Eyebrow><h1>{title.split("\n").map((x,i)=><span key={i}>{x}</span>)}</h1></div></section>}
export function ImpactPage(){return <Shell><main><section className="impact-hero"><Eyebrow>Impact / Pupsart Network</Eyebrow><h1>GOOD LOOKS.<br/><em>VISIBLE GOOD.</em></h1><p>Una parte definita del valore di ogni ordine sosterrà progetti verificabili per il benessere animale.</p><span className="status">NETWORK IN COSTRUZIONE</span></section><section className="impact-model"><div><Eyebrow>Modello consigliato</Eyebrow><h2>Un importo fisso per ordine.</h2><p>Più semplice da capire, comunicare e verificare. Il valore resta da definire sui margini reali.</p></div><div className="amount">€X<span>devoluti per ordine</span></div></section><section className="transparency"><Eyebrow>Trasparenza</Eyebrow>{[["01","Importo","Quanto viene destinato per ogni ordine"],["02","Partner","Chi riceve il contributo"],["03","Progetto","A cosa servono i fondi"],["04","Risultato","Quanto è stato trasferito e cosa è successo"]].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</section><section className="network-empty"><div><Eyebrow>Directory partner</Eyebrow><h2>La rete prende forma.</h2><p>Nessun canile o associazione è ancora presentato come partner ufficiale. Pubblicheremo criteri, schede progetto e report prima di attivare la raccolta.</p></div><form onSubmit={e=>e.preventDefault()}><h3>Entra nella rete</h3><label>Nome associazione<input required/></label><label>Email<input required type="email"/></label><label>Il vostro progetto<textarea/></label><button className="button button-dark">Invia candidatura</button></form></section></main></Shell>}
export function CommunityPage(){return <Shell><main><PageHero label="Community / Journal 001" title="DOGS, PEOPLE,\nPLACES." image={images.popup} alt="Pop-up Pupsart con installazione a forma di zampa in piazza del Duomo"/><section className="magazine"><article className="lead"><Image src={images.gallery} fill sizes="66vw" alt="Persone e cani a un evento Pupsart in galleria"/><div><Eyebrow>Main Characters</Eyebrow><h2>Una città piena di carattere.</h2><p>Ritratti, studi creativi e storie di chi vive il cane come presenza, non come accessorio.</p></div></article>{["Dogs at Work","City Icons","Home Stories","Pupsart People"].map((x,i)=><article className="story" key={x}><span>0{i+2}</span><h3>{x}</h3><p>Rubrica editoriale in preparazione.</p></article>)}</section><section className="submit-story"><Eyebrow>Open call</Eyebrow><h2>Tu, il tuo cane, la vostra città.</h2><p>Invia una storia per le prossime rubriche Pupsart.</p><button className="button button-coral">Proponi la tua storia</button></section></main></Shell>}
export function ShopPage(){return <Shell><main><PageHero label="Human Shop / Preview" title="MADE FOR PEOPLE\nWITH STANDARDS." image={images.fashion} alt="Capsule Pupsart con apparel e accessori illustrati"/><section className="shop-intro"><div><Eyebrow>Capsule 02</Eyebrow><h2>Wear the character.</h2></div><p>Una preview editoriale della futura collezione. Nessun articolo è ancora in vendita e nessun prezzo è stato definito.</p></section><div className="shop-filters" aria-label="Filtri collezione">{["Tutto","Apparel","Tote","Zine","Desk objects"].map(x=><button key={x}>{x}</button>)}</div><section className="product-grid">{["T-shirt / Main Character","Tote / Good Taste","Cap / Pupsart Paw","Zine / Issue 001"].map((x,i)=><article key={x}><div className={`product-visual visual-${i}`}><span>COMING SOON</span></div><h3>{x}</h3><p>Materiali e dettagli da definire.</p><button>Avvisami al lancio <ArrowUpRight/></button></article>)}</section><Newsletter/></main></Shell>}
export function AboutPage(){return <Shell><main><section className="about-hero"><Eyebrow>About / Brand foundation</Eyebrow><h1>ARTE, STILE,<br/>COMPAGNIA,<br/><em>IMPATTO.</em></h1></section><section className="about-grid"><div><h2>Pupsart rende la cultura pet più bella, contemporanea e utile.</h2></div><div><p>Nasce dalla convinzione che un cane sia un compagno di vita, una presenza emotiva e una parte visibile della nostra identità.</p><p>Il ritratto personalizzato apre la porta a un sistema di arte, oggetti, capsule e collaborazioni costruito con poche idee forti.</p></div></section><section className="brand-territory"><Image src={images.smoked} fill sizes="100vw" alt="Interno sofisticato con ritratto di bassotto Pupsart"/><div><Eyebrow>Il nostro territorio</Eyebrow><h2>Gallery shop.<br/>Fashion attitude.<br/>Dog culture.</h2></div></section></main></Shell>}
export function ServicePage({title}:{title:string}){return <Shell><main className="service-page"><Eyebrow>Pupsart / Informazioni</Eyebrow><h1>{title}</h1><p>Questa pagina è predisposta per i contenuti ufficiali. I termini definitivi verranno pubblicati prima dell’apertura degli ordini.</p><Link className="text-link" href="/">Torna alla homepage <ArrowUpRight/></Link></main></Shell>}
